# Generated by Django 4.0.5 on 2022-06-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinia',
            name='Nick',
        ),
        migrations.RemoveField(
            model_name='zwrot',
            name='Nick',
        ),
        migrations.DeleteModel(
            name='Klient',
        ),
        migrations.DeleteModel(
            name='Opinia',
        ),
        migrations.DeleteModel(
            name='Zwrot',
        ),
    ]
