# Generated by Django 4.0.5 on 2022-06-18 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aplikacja', '0002_remove_opinia_nick_remove_zwrot_nick_delete_klient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('idAdres', models.IntegerField(primary_key=True, serialize=False)),
                ('kodPocztowy', models.CharField(max_length=6)),
                ('Miasto', models.CharField(max_length=30)),
                ('Ulica', models.CharField(max_length=20)),
                ('nrDomu', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('Nick', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Imie', models.CharField(max_length=50)),
                ('Nazwisko', models.CharField(max_length=50)),
                ('nrTelefonu', models.CharField(max_length=9)),
                ('Email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Krawiec',
            fields=[
                ('idKrawiec', models.IntegerField(primary_key=True, serialize=False)),
                ('Imie', models.CharField(max_length=50)),
                ('Nazwisko', models.CharField(max_length=50)),
                ('nrTelefonu', models.CharField(max_length=9)),
                ('Email', models.CharField(max_length=30)),
                ('idAdres', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplikacja.adres')),
            ],
        ),
        migrations.CreateModel(
            name='Zwrot',
            fields=[
                ('idZwrot', models.IntegerField(primary_key=True, serialize=False)),
                ('Powod', models.CharField(max_length=256)),
                ('dataWyslania', models.DateField()),
                ('dataOtrzymania', models.DateField()),
                ('czyZwroconoPieniadze', models.BooleanField()),
                ('Nick', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplikacja.klient')),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('idZamowienie', models.IntegerField(primary_key=True, serialize=False)),
                ('sposobPlatnosci', models.CharField(max_length=30)),
                ('dataZamowienia', models.DateField()),
                ('dataWyslania', models.DateField()),
                ('dataDostarczenia', models.DateField()),
                ('Nick', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplikacja.klient')),
            ],
        ),
        migrations.CreateModel(
            name='Towar',
            fields=[
                ('idTowar', models.IntegerField(primary_key=True, serialize=False)),
                ('Nazwa', models.CharField(max_length=50)),
                ('Material', models.CharField(max_length=20)),
                ('Cena', models.IntegerField()),
                ('idKrawiec', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplikacja.krawiec')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalizoawnyTowar',
            fields=[
                ('idPersonalizowany', models.IntegerField(primary_key=True, serialize=False)),
                ('Rozmiar', models.CharField(max_length=6)),
                ('Kolor', models.CharField(max_length=20)),
                ('czyWyprodukowano', models.BooleanField()),
                ('idTowar', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplikacja.towar')),
                ('idZamowienie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplikacja.zamowienie')),
                ('idZwrot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplikacja.zwrot')),
            ],
        ),
        migrations.CreateModel(
            name='Opinia',
            fields=[
                ('idOpinia', models.IntegerField(primary_key=True, serialize=False)),
                ('Gwiazdki', models.IntegerField()),
                ('Komentarz', models.CharField(max_length=256)),
                ('Nick', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplikacja.klient')),
                ('idTowar', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplikacja.towar')),
            ],
        ),
    ]
