# Generated by Django 4.0.5 on 2022-06-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalizoawnyTowar',
            new_name='PersonalizowanyTowar',
        ),
    ]
