# Generated by Django 4.0.5 on 2022-06-18 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0004_rename_personalizoawnytowar_personalizowanytowar'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='idAdres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplikacja.adres'),
        ),
    ]
