# Generated by Django 4.0.5 on 2022-06-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0007_remove_zamowienie_sposobplatnosci'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='sposobPlatnosci',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
