# Generated by Django 4.0.5 on 2022-06-18 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0008_zamowienie_sposobplatnosci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizowanytowar',
            name='idZamowienie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplikacja.zamowienie'),
        ),
    ]
