# Generated by Django 4.0.5 on 2022-06-21 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0009_alter_personalizowanytowar_idzamowienie'),
    ]

    operations = [
        migrations.AddField(
            model_name='zwrot',
            name='Towar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplikacja.towar'),
        ),
        migrations.AlterField(
            model_name='zwrot',
            name='Nick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplikacja.klient'),
        ),
    ]
