# Generated by Django 4.0.5 on 2022-06-21 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0010_zwrot_towar_alter_zwrot_nick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizowanytowar',
            name='idZwrot',
        ),
        migrations.AlterField(
            model_name='klient',
            name='idAdres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplikacja.adres'),
        ),
        migrations.AlterField(
            model_name='krawiec',
            name='idAdres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplikacja.adres'),
        ),
        migrations.AlterField(
            model_name='opinia',
            name='Nick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplikacja.klient'),
        ),
        migrations.AlterField(
            model_name='opinia',
            name='idTowar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplikacja.towar'),
        ),
        migrations.AlterField(
            model_name='personalizowanytowar',
            name='idTowar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplikacja.towar'),
        ),
        migrations.AlterField(
            model_name='personalizowanytowar',
            name='idZamowienie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplikacja.zamowienie'),
        ),
        migrations.AlterField(
            model_name='towar',
            name='idKrawiec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplikacja.krawiec'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='Nick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplikacja.klient'),
        ),
    ]
