# Generated by Django 4.0.5 on 2022-06-21 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0011_remove_personalizowanytowar_idzwrot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizowanytowar',
            name='idTowar',
            field=models.ForeignKey(blank=True, default=100, on_delete=django.db.models.deletion.CASCADE, to='aplikacja.towar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalizowanytowar',
            name='idZamowienie',
            field=models.ForeignKey(blank=True, default=100, on_delete=django.db.models.deletion.CASCADE, to='aplikacja.zamowienie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='towar',
            name='idKrawiec',
            field=models.ForeignKey(blank=True, default=100, on_delete=django.db.models.deletion.CASCADE, to='aplikacja.krawiec'),
            preserve_default=False,
        ),
    ]
